[snap] Add Snapcraft packaging for Ubuntu installation -- not yet working
Packaging and installation are going fine, but the application fails
due to missing or wrong kind of UTF-8 support when trying to create
a window via Pyglet:

  pyglet.window.xlib.XlibException: Could not create UTF8 text property